mysite/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^plotter/', include('plotter.urls')),
    url(r'^admin/', admin.site.urls),
]

plotter/urls.py
from django.conf.urls import url

from . import views

app_name = 'plotter'
urlpatterns = [
    # ex: /plotter/
    url(r'^$', views.index, name='index'),
    # ex: /plotter/plot/
    url(r'^plot/$', views.plot, name='plot'),
    # ex: /plotter/plot_5/results/
    url(r'^plot_(?P<plot_id>[0-9]+)/results/$', views.results, name='results'),
    # ex: /plotter/plot_5/edit/
    url(r'^plot_(?P<plot_id>[0-9]+)/edit/$', views.edit, name='edit'),
    # ex: /plotter/posted/
    url(r'^posted/$', views.posted, name='posted'),
]

plotter/models.py
from django.db import models


class Plot(models.Model):
    name = models.CharField(max_length=40)
    left = models.CharField(max_length=40)
    right = models.CharField(max_length=40)
    top = models.CharField(max_length=40)
    bottom = models.CharField(max_length=40)
    creation_date = models.DateTimeField()
    def __str__(self):
        return str(self.id) + ': ' + self.name    

class Point(models.Model):
    name = models.CharField(max_length=20)
    color = models.CharField(max_length=6, null=True)
    x = models.IntegerField()
    y = models.IntegerField()
    belong_plot = models.ForeignKey(Plot, on_delete=models.CASCADE)
    def __str__(self):
        return self.name + ' (map' + str(self.belong_plot) + ')'

plotter/views.py
from django.http import HttpResponse
from django.template import loader
from django.shortcuts import get_object_or_404, render
from django.utils import timezone

from .models import Plot, Point

from mpl_toolkits.axes_grid.axislines import SubplotZero
import matplotlib.pyplot as plt
import numpy as np


def index(request):
    return render(request, 'plotter/index.html')

def plot(request):
    if request.POST['plot_name']:
        plot_name = request.POST['plot_name']
    else:
        plot_name = None
    left = request.POST['left']
    right = request.POST['right']
    top = request.POST['top']
    bottom = request.POST['bottom']

    points = []
    points_x = []
    points_y = []

    for count in range(100):
        point_num = count + 1
        try:
            points.append(request.POST['point_name_%s' % point_num])
            points_x.append(float(request.POST['point_x_%s' % point_num]) - 300) # float() is just for test
            points_y.append(300 - float(request.POST['point_y_%s' % point_num])) # float() is just for test
        except:
            break

    if 1:
        fig = plt.figure(1)
        ax = SubplotZero(fig, 111)
        fig.add_subplot(ax)

        for direction in ["xzero", "yzero"]:
            ax.axis[direction].set_visible(True)

        for direction in ["left", "right", "bottom", "top"]:
            ax.axis[direction].set_visible(False)

    plt.scatter(points_x, points_y)
    for point, x, y in zip(points, points_x, points_y):
        plt.annotate(point, xy=(x, y), xytext=(5, -5), textcoords='offset points')

    plt.gca().set_xlim([0, 600])
    plt.gca().set_ylim([0, 600])
    plt.axis("equal")
    plt.xlabel('%s - %s' % (left, right), fontdict={'family': 'Arial'})
    plt.ylabel('%s - %s' % (bottom, top), fontdict={'family': 'Arial'})
    plt.title(plot_name)

    plt.show()

    # context = {
    #     'plot': new_plot,
    #     'plot_id': new_plot.id,
    # }
    # return render(request, 'plotter/results.html', context)

def results(request, plot_id):
    plot = Plot.objects.get(pk=plot_id)
    context = {
        'plot': plot,
        'plot_id': plot_id,
    }
    return render(request, 'plotter/results.html', context)

def edit(request, plot_id):
    return HttpResponse("You're editing plot %s." % plot_id)

def posted(request):
    return render(request, 'plotter/posted.html')

plotter/templates/plotter/edit.html
<!DOCTYPE html>
<html>

    <head>
        <meta charset="UTF-8">
        <title>plotter - edit plot{{ plot_id }}</title>
        {% load static %}
        <link rel="stylesheet" type="text/css" href="{% static 'plotter/style.css' %}" />
    </head>

    <body>
        <p>You're editing plot {{ plot_id }}.</p>
    </body>

</html>

plotter/templates/plotter/index.html
<!DOCTYPE html>
<html>

    <head>
        <meta charset="UTF-8">
        <title>plotter</title>
        {% load static %}
        <link rel="stylesheet" type="text/css" href="{% static 'plotter/style.css' %}" />
    </head>

    <body>
        <h1>plotter</h1>
        <form action="{% url 'plotter:plot' %}" method="post">
            {% csrf_token %}
            <p><label for="plot_name">title(optional)<input type="text" name="plot_name" size="60" class="title"></label></p>
            <p>double-click to add point</p>
            <div class="plot_whole">
                <div class="top">
                    <label for="top"><input type="text" name="top" /></label>
                </div>
                <div class="clearfix">
                    <div class="left">
                        <label for="left"><input type="text" name="left" /></label>
                    </div>
                    <div id="plot_area">
                    </div>
                    <div class="right">
                        <label for="right"><input type="text" name="right" /></label>
                    </div>
                </div>
                <div class="bottom">
                    <label for="bottom"><input type="text" name="bottom" /></label>
                </div>
            </div>
            <input type="submit" value="plot" class="button">
        </form>

        <a href="{% url 'plotter:edit' 100 %}"><p>[for test] edit plot100</p></a>
        <a href="{% url 'plotter:plot' %}"><p>[for test] plot</p></a>
    </body>

    <script type="text/javascript" src="{% static 'plotter/js/jquery-3.2.1.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'plotter/js/add_points.js' %}"></script>

</html>

plotter/templates/plotter/posted.html
<!DOCTYPE html>
<html>

    <head>
        <meta charset="UTF-8">
        <title>plotter - posted</title>
        {% load static %}
        <link rel="stylesheet" type="text/css" href="{% static 'plotter/style.css' %}" />
    </head>

    <body>
        <p>your plot has posted successfully!</p>

        <p><a href="{% url 'plotter:index' %}">plot more</a></p>
    </body>

</html>

plotter/templates/plotter/results.html
<!DOCTYPE html>
<html>

    <head>
        <meta charset="UTF-8">
        <title>plotter - results</title>
        {% load static %}
        <link rel="stylesheet" type="text/css" href="{% static 'plotter/style.css' %}" />
    </head>

    <body>
        <p>{{ plot.name }}</p>
        <div class="plot_whole">
            <div class="top">
                <p>{{ plot.top }}</p>
            </div>
            <div class="clearfix">
                <div class="left">
                    <p>{{ plot.left }}</p>
                </div>
                <div id="plot_area">
                    {% for point in plot.point_set.all %}

                    {% endfor %}
                </div>
                <div class="right">
                    <p>{{ plot.right }}</p>
                </div>
            </div>
            <div class="bottom">
                <p>{{ plot.bottom }}</p>
            </div>
        </div>

        <p><a href="{% url 'plotter:posted' %}">post this plot to SNS</a></p>

        <p><a href="{% url 'plotter:index' %}">plot more</a></p>
    </body>

    <script type="text/javascript" src="{% static 'plotter/js/jquery-3.2.1.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'plotter/js/show_points.js' %}"></script>

</html>

templates/plotter/edit.html
<!DOCTYPE html>
<html>

    <head>
        <meta charset="UTF-8">
        <title>plotter - edit plot{{ plot_id }}</title>
        {% load static %}
        <link rel="stylesheet" type="text/css" href="{% static 'plotter/style.css' %}" />
    </head>

    <body>
        <p>You're editing plot {{ map_id }}.</p>
    </body>

</html>

templates/plotter/index.html
<!DOCTYPE html>
<html>

    <head>
        <meta charset="UTF-8">
        <title>plotter</title>
        {% load static %}
        <link rel="stylesheet" type="text/css" href="{% static 'plotter/style.css' %}" />
    </head>

    <body>
        <h1>plotter</h1>
        <form acrion="{% url 'plotter:plot' %}" method="post">
            {% csrf_token %}
            <p><label for="plot_name">title(optional)<input type="text" name="plot_name" size="60" class="title"></label></p>
            <div class="plot_area">
                <div class="right">
                    <label for="right"><input type="text" name="right" value="right" /></label>
                </div>
                <div class="clearfix">
                    <div class="bottom">
                        <label for="bottom"><input type="text" name="bottom" value="bottom" /></label>
                    </div>
                    <div class="field">
                    </div>
                    <div class="top">
                        <label for="top"><input type="text" name="top" value="y2" /></label>
                    </div>
                </div>
                <div class="left">
                    <label for="left"><input type="text" name="left" value="left" /></label>
                </div>
            </div>
            <input type="submit" value="plot" class="button">
        </form>

        <a href="{% url 'plotter:edit' 100 %}"><p>[for test] edit plot100</p></a>
        <a href="{% url 'plotter:plot' %}"><p>[for test] plot</p></a>
    </body>

</html>